### PR TITLE
Actually ship the extension files

### LINKED ISSUE #3: Package doesn't ship any extension files
Currently, this extension doesn't ship any files. Just download a tar ball from https://anaconda.org/conda-forge/vscode-icons/files and take a look. That's probably because the package was built with an old version of code-server before https://github.com/conda-forge/code-server-feedstock/pull/40. Also, we're pinning code-server to a version that doesn't exist. The code-server version that was based on vscode 1.40.2 was 2.1698.

_Update:_ Ah, with the second build that popped up on conda-forge after I opened this issue (triggered by ~#2~ #4 😁 ), things magically show up. That seems to have been built with the latest code-server version.

### PR DESCRIPTION
**Pull request by jtilly**
Also pin code-server at >=3.6.0, which is when we began pinning nodejs at 12.*.

Closes #3 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by janjagusch** [comment]
Hi!

Thanks for opening this PR. Some thoughts:

* With the changes made in https://github.com/conda-forge/code-server-feedstock/pull/40, specifying the `--extensions-dir` should not be necessary anymore.
* Regarding the current `code-server` pin: Thanks for bringing that up! `vscode-icons` requires `vscode>=1.40.2` and apparently back then I still thought that `code-server` and `vscode` have the same versioning (which is not the case). I feel like we could probably go lower than `3.6` (the latest v2 release already runs run `vscode>1.40.2`) but it also seems like a reasonable requirement, considering the release is already 3 months old.

So, moving forward I'd suggest to remove all the explicit `--extensions-dir` code again and focus on the pin change for `code-server`. What do you think? @jtilly

**Review by janjagusch — COMMENTED** [review]
Hi!

Thanks for opening this PR. Some thoughts:

* With the changes made in https://github.com/conda-forge/code-server-feedstock/pull/40, specifying the `--extensions-dir` should not be necessary anymore.
* Regarding the current `code-server` pin: Thanks for bringing that up! `vscode-icons` requires `vscode>=1.40.2` and apparently back then I still thought that `code-server` and `vscode` have the same versioning (which is not the case). I feel like we could probably go lower than `3.6` (the latest v2 release already runs run `vscode>1.40.2`) but it also seems like a reasonable requirement, considering the release is already 3 months old.

So, moving forward I'd suggest to remove all the explicit `--extensions-dir` code again and focus on the pin change for `code-server`. What do you think? @jtilly

**Comment by jtilly** [comment]
> With the changes made in conda-forge/code-server-feedstock#40, specifying the --extensions-dir should not be necessary anymore.

Sure, but then you should be pinning code-server to the version that specifies the `--extension-dir`. When I was building the package locally (on osx), I ended up with nodejs 14.* and code-server 3.5 in my build environment and nothing ended up in the package.

**Comment by xhochy** [comment]
Fixed by #5

**Comment by xhochy** [comment]
@jtilly Please never push to the main conda-forge repo ;)

**Pull request closed without merging**
